# Generated by Django 3.2.7 on 2021-09-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('base_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social_scrapper.socialmedia')),
            ],
            options={
                'unique_together': {('username', 'social_media')},
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social_scrapper.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('metadata', models.JSONField(null=True)),
                ('status', models.CharField(choices=[('FOUND', 'FOUND'), ('SENT', 'SENT'), ('WORKING', 'WORKIN'), ('DONE', 'DONE'), ('ERROR', 'ERROR'), ('MISSING', 'MISSING')], max_length=10)),
                ('post_type', models.CharField(default='Image', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social_scrapper.socialmediauser')),
            ],
        ),
    ]
