# Generated by Django 3.2.8 on 2021-10-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('FOUND', 'FOUND'), ('SENT', 'SENT'), ('WORKING', 'WORKING'), ('DONE', 'DONE'), ('ERROR', 'ERROR'), ('MISSING', 'MISSING')], max_length=10),
        ),
    ]
